name: estacionai
description: Gerenciamento de um estacionamento de caminhões.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  provider: ^6.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.19.5

flutter:

  uses-material-design: true

